### ISSUE TITLE
Cx Freeze ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python'

### ISSUE THREAD

**Issue by Lucysmith8** [anthony-tuininga/cx_Freeze#670] opened 2020-06-11 14:05 UTC
I use cx freeze to distribute my application with TKinter. Everything works perfectly, but I have a problem with only one module, it's tensorflow. When I run my script from conda, tensorflow works perfectly. But when I freeze with pip setup.py build, I have a problem.

Windows 10
cx-Freeze 6.1
Tensorflow 2.0
Python 3.7

    Studio\Shared\Python37_64\lib\site-packages\tensorflow_init_.py", line 99, in 

    from tensorflow_core import *

    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core_init_.py", line 28, in 

    from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import

    ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)

**Comment by marcelotduarte** [comment] 2020-06-11 22:34
Duplicate of #646

**Closed by marcelotduarte** 2020-06-11 22:34 UTC
